build: setup docker
mtoanp/docker-user pull request #2
Opened 2024-08-01 10:45 UTC by mtoanp

added 
docker-compose
. backend/ 
  Dockerfile
  .dockerignore

2024-08-01 12:25 UTC, nyukeit commented
Received error
<img width="840" alt="Screenshot 2024-08-01 at 14 24 02" src="https://github.com/user-attachments/assets/23873944-e172-436f-9ccf-61f3f90558a2">

2024-08-01 12:33 UTC, nyukeit commented
Found the culprit
Dockerfile -> WORKDIR /app  ❌❌
Dockerfile -> WORKDIR ./

2024-08-01 12:37 UTC, nyukeit requested changes
See review changes before merging

2024-08-01 12:37 UTC, nyukeit commented on backend/Dockerfile
Change WORKDIR /app to WORKDIR ./

2024-08-01 12:37 UTC, nyukeit commented on docker-compose.yml
Remove `version: 3.7`
Reason -> Version is depcrecated

2024-08-02 10:44 UTC, mtoanp commented
> Received error <img alt="Screenshot 2024-08-01 at 14 24 02" width="840" src="https://private-user-images.githubusercontent.com/60096756/354220605-23873944-e172-436f-9ccf-61f3f90558a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTUzOTgsIm5iZiI6MTcyMjU5NTA5OCwicGF0aCI6Ii82MDA5Njc1Ni8zNTQyMjA2MDUtMjM4NzM5NDQtZTE3Mi00MzZmLTljY2YtNjFmM2Y5MDU1OGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDEwMzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NmViMjU0YmIzZjRkY2I5OGEyNzRkZWQzYzUzZGNjNzY0ZDBhZGU5MTc1MmUwM2U2NjIzMmZhZjEzMjNmMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GEKjPTGp9uSOT5A2vcQS1DJAxGsrofs5n4wnPKKhvL4">

Il faut install dependencies manuellement pour backend

2024-08-02 10:46 UTC, mtoanp commented on docker-compose.yml
version: 3.7 est il la version de docker-compose ?

2024-08-02 11:50 UTC, nyukeit commented on docker-compose.yml
https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313

2024-08-02 11:50 UTC, nyukeit commented on backend/Dockerfile
-- a ignorer -- le WORKDIR est toujours /app

2024-08-02 11:52 UTC, nyukeit commented
> > Received error <img alt="Screenshot 2024-08-01 at 14 24 02" width="840" src="https://private-user-images.githubusercontent.com/60096756/354220605-23873944-e172-436f-9ccf-61f3f90558a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1OTUzOTgsIm5iZiI6MTcyMjU5NTA5OCwicGF0aCI6Ii82MDA5Njc1Ni8zNTQyMjA2MDUtMjM4NzM5NDQtZTE3Mi00MzZmLTljY2YtNjFmM2Y5MDU1OGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDEwMzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NmViMjU0YmIzZjRkY2I5OGEyNzRkZWQzYzUzZGNjNzY0ZDBhZGU5MTc1MmUwM2U2NjIzMmZhZjEzMjNmMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GEKjPTGp9uSOT5A2vcQS1DJAxGsrofs5n4wnPKKhvL4">
> 
> Il faut install dependencies manuellement pour backend

Oui ca marche maintenant...regarde le nouveau PR

2024-08-11 08:53 UTC, closed without merging